/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthImport } from './routes/auth'
import { Route as AppImport } from './routes/app'
import { Route as RootLayoutImport } from './routes/_root-layout'
import { Route as AppIndexImport } from './routes/app/index'
import { Route as RootLayoutIndexImport } from './routes/_root-layout/index'
import { Route as AuthSignupImport } from './routes/auth/signup'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as RootLayoutTutorialImport } from './routes/_root-layout/tutorial'
import { Route as AppProfileIndexImport } from './routes/app/profile/index'
import { Route as AppJoinRoomIndexImport } from './routes/app/join-room/index'
import { Route as AppEditProfileIndexImport } from './routes/app/edit-profile/index'
import { Route as AppCreateRoomIndexImport } from './routes/app/create-room/index'
import { Route as AppRoomIdImport } from './routes/app/room/$id'
import { Route as AppRoomIdIndexImport } from './routes/app/room/$id/index'
import { Route as AppRoomIdResultsIndexImport } from './routes/app/room/$id/results/index'
import { Route as AppRoomIdGameIndexImport } from './routes/app/room/$id/game/index'
import { Route as AppRoomIdChatIndexImport } from './routes/app/room/$id/chat/index'

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const AppRoute = AppImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRoute,
} as any)

const RootLayoutRoute = RootLayoutImport.update({
  id: '/_root-layout',
  getParentRoute: () => rootRoute,
} as any)

const AppIndexRoute = AppIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)

const RootLayoutIndexRoute = RootLayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RootLayoutRoute,
} as any)

const AuthSignupRoute = AuthSignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)

const RootLayoutTutorialRoute = RootLayoutTutorialImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => RootLayoutRoute,
} as any)

const AppProfileIndexRoute = AppProfileIndexImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AppRoute,
} as any)

const AppJoinRoomIndexRoute = AppJoinRoomIndexImport.update({
  id: '/join-room/',
  path: '/join-room/',
  getParentRoute: () => AppRoute,
} as any)

const AppEditProfileIndexRoute = AppEditProfileIndexImport.update({
  id: '/edit-profile/',
  path: '/edit-profile/',
  getParentRoute: () => AppRoute,
} as any)

const AppCreateRoomIndexRoute = AppCreateRoomIndexImport.update({
  id: '/create-room/',
  path: '/create-room/',
  getParentRoute: () => AppRoute,
} as any)

const AppRoomIdRoute = AppRoomIdImport.update({
  id: '/room/$id',
  path: '/room/$id',
  getParentRoute: () => AppRoute,
} as any)

const AppRoomIdIndexRoute = AppRoomIdIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoomIdRoute,
} as any)

const AppRoomIdResultsIndexRoute = AppRoomIdResultsIndexImport.update({
  id: '/results/',
  path: '/results/',
  getParentRoute: () => AppRoomIdRoute,
} as any)

const AppRoomIdGameIndexRoute = AppRoomIdGameIndexImport.update({
  id: '/game/',
  path: '/game/',
  getParentRoute: () => AppRoomIdRoute,
} as any)

const AppRoomIdChatIndexRoute = AppRoomIdChatIndexImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => AppRoomIdRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_root-layout': {
      id: '/_root-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof RootLayoutImport
      parentRoute: typeof rootRoute
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_root-layout/tutorial': {
      id: '/_root-layout/tutorial'
      path: '/tutorial'
      fullPath: '/tutorial'
      preLoaderRoute: typeof RootLayoutTutorialImport
      parentRoute: typeof RootLayoutImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof AuthImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupImport
      parentRoute: typeof AuthImport
    }
    '/_root-layout/': {
      id: '/_root-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof RootLayoutIndexImport
      parentRoute: typeof RootLayoutImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexImport
      parentRoute: typeof AppImport
    }
    '/app/room/$id': {
      id: '/app/room/$id'
      path: '/room/$id'
      fullPath: '/app/room/$id'
      preLoaderRoute: typeof AppRoomIdImport
      parentRoute: typeof AppImport
    }
    '/app/create-room/': {
      id: '/app/create-room/'
      path: '/create-room'
      fullPath: '/app/create-room'
      preLoaderRoute: typeof AppCreateRoomIndexImport
      parentRoute: typeof AppImport
    }
    '/app/edit-profile/': {
      id: '/app/edit-profile/'
      path: '/edit-profile'
      fullPath: '/app/edit-profile'
      preLoaderRoute: typeof AppEditProfileIndexImport
      parentRoute: typeof AppImport
    }
    '/app/join-room/': {
      id: '/app/join-room/'
      path: '/join-room'
      fullPath: '/app/join-room'
      preLoaderRoute: typeof AppJoinRoomIndexImport
      parentRoute: typeof AppImport
    }
    '/app/profile/': {
      id: '/app/profile/'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileIndexImport
      parentRoute: typeof AppImport
    }
    '/app/room/$id/': {
      id: '/app/room/$id/'
      path: '/'
      fullPath: '/app/room/$id/'
      preLoaderRoute: typeof AppRoomIdIndexImport
      parentRoute: typeof AppRoomIdImport
    }
    '/app/room/$id/chat/': {
      id: '/app/room/$id/chat/'
      path: '/chat'
      fullPath: '/app/room/$id/chat'
      preLoaderRoute: typeof AppRoomIdChatIndexImport
      parentRoute: typeof AppRoomIdImport
    }
    '/app/room/$id/game/': {
      id: '/app/room/$id/game/'
      path: '/game'
      fullPath: '/app/room/$id/game'
      preLoaderRoute: typeof AppRoomIdGameIndexImport
      parentRoute: typeof AppRoomIdImport
    }
    '/app/room/$id/results/': {
      id: '/app/room/$id/results/'
      path: '/results'
      fullPath: '/app/room/$id/results'
      preLoaderRoute: typeof AppRoomIdResultsIndexImport
      parentRoute: typeof AppRoomIdImport
    }
  }
}

// Create and export the route tree

interface RootLayoutRouteChildren {
  RootLayoutTutorialRoute: typeof RootLayoutTutorialRoute
  RootLayoutIndexRoute: typeof RootLayoutIndexRoute
}

const RootLayoutRouteChildren: RootLayoutRouteChildren = {
  RootLayoutTutorialRoute: RootLayoutTutorialRoute,
  RootLayoutIndexRoute: RootLayoutIndexRoute,
}

const RootLayoutRouteWithChildren = RootLayoutRoute._addFileChildren(
  RootLayoutRouteChildren,
)

interface AppRoomIdRouteChildren {
  AppRoomIdIndexRoute: typeof AppRoomIdIndexRoute
  AppRoomIdChatIndexRoute: typeof AppRoomIdChatIndexRoute
  AppRoomIdGameIndexRoute: typeof AppRoomIdGameIndexRoute
  AppRoomIdResultsIndexRoute: typeof AppRoomIdResultsIndexRoute
}

const AppRoomIdRouteChildren: AppRoomIdRouteChildren = {
  AppRoomIdIndexRoute: AppRoomIdIndexRoute,
  AppRoomIdChatIndexRoute: AppRoomIdChatIndexRoute,
  AppRoomIdGameIndexRoute: AppRoomIdGameIndexRoute,
  AppRoomIdResultsIndexRoute: AppRoomIdResultsIndexRoute,
}

const AppRoomIdRouteWithChildren = AppRoomIdRoute._addFileChildren(
  AppRoomIdRouteChildren,
)

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppRoomIdRoute: typeof AppRoomIdRouteWithChildren
  AppCreateRoomIndexRoute: typeof AppCreateRoomIndexRoute
  AppEditProfileIndexRoute: typeof AppEditProfileIndexRoute
  AppJoinRoomIndexRoute: typeof AppJoinRoomIndexRoute
  AppProfileIndexRoute: typeof AppProfileIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppRoomIdRoute: AppRoomIdRouteWithChildren,
  AppCreateRoomIndexRoute: AppCreateRoomIndexRoute,
  AppEditProfileIndexRoute: AppEditProfileIndexRoute,
  AppJoinRoomIndexRoute: AppJoinRoomIndexRoute,
  AppProfileIndexRoute: AppProfileIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof RootLayoutRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/tutorial': typeof RootLayoutTutorialRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/': typeof RootLayoutIndexRoute
  '/app/': typeof AppIndexRoute
  '/app/room/$id': typeof AppRoomIdRouteWithChildren
  '/app/create-room': typeof AppCreateRoomIndexRoute
  '/app/edit-profile': typeof AppEditProfileIndexRoute
  '/app/join-room': typeof AppJoinRoomIndexRoute
  '/app/profile': typeof AppProfileIndexRoute
  '/app/room/$id/': typeof AppRoomIdIndexRoute
  '/app/room/$id/chat': typeof AppRoomIdChatIndexRoute
  '/app/room/$id/game': typeof AppRoomIdGameIndexRoute
  '/app/room/$id/results': typeof AppRoomIdResultsIndexRoute
}

export interface FileRoutesByTo {
  '/auth': typeof AuthRouteWithChildren
  '/tutorial': typeof RootLayoutTutorialRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/': typeof RootLayoutIndexRoute
  '/app': typeof AppIndexRoute
  '/app/create-room': typeof AppCreateRoomIndexRoute
  '/app/edit-profile': typeof AppEditProfileIndexRoute
  '/app/join-room': typeof AppJoinRoomIndexRoute
  '/app/profile': typeof AppProfileIndexRoute
  '/app/room/$id': typeof AppRoomIdIndexRoute
  '/app/room/$id/chat': typeof AppRoomIdChatIndexRoute
  '/app/room/$id/game': typeof AppRoomIdGameIndexRoute
  '/app/room/$id/results': typeof AppRoomIdResultsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_root-layout': typeof RootLayoutRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_root-layout/tutorial': typeof RootLayoutTutorialRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/_root-layout/': typeof RootLayoutIndexRoute
  '/app/': typeof AppIndexRoute
  '/app/room/$id': typeof AppRoomIdRouteWithChildren
  '/app/create-room/': typeof AppCreateRoomIndexRoute
  '/app/edit-profile/': typeof AppEditProfileIndexRoute
  '/app/join-room/': typeof AppJoinRoomIndexRoute
  '/app/profile/': typeof AppProfileIndexRoute
  '/app/room/$id/': typeof AppRoomIdIndexRoute
  '/app/room/$id/chat/': typeof AppRoomIdChatIndexRoute
  '/app/room/$id/game/': typeof AppRoomIdGameIndexRoute
  '/app/room/$id/results/': typeof AppRoomIdResultsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/app'
    | '/auth'
    | '/tutorial'
    | '/auth/login'
    | '/auth/signup'
    | '/'
    | '/app/'
    | '/app/room/$id'
    | '/app/create-room'
    | '/app/edit-profile'
    | '/app/join-room'
    | '/app/profile'
    | '/app/room/$id/'
    | '/app/room/$id/chat'
    | '/app/room/$id/game'
    | '/app/room/$id/results'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/tutorial'
    | '/auth/login'
    | '/auth/signup'
    | '/'
    | '/app'
    | '/app/create-room'
    | '/app/edit-profile'
    | '/app/join-room'
    | '/app/profile'
    | '/app/room/$id'
    | '/app/room/$id/chat'
    | '/app/room/$id/game'
    | '/app/room/$id/results'
  id:
    | '__root__'
    | '/_root-layout'
    | '/app'
    | '/auth'
    | '/_root-layout/tutorial'
    | '/auth/login'
    | '/auth/signup'
    | '/_root-layout/'
    | '/app/'
    | '/app/room/$id'
    | '/app/create-room/'
    | '/app/edit-profile/'
    | '/app/join-room/'
    | '/app/profile/'
    | '/app/room/$id/'
    | '/app/room/$id/chat/'
    | '/app/room/$id/game/'
    | '/app/room/$id/results/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  RootLayoutRoute: typeof RootLayoutRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  RootLayoutRoute: RootLayoutRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_root-layout",
        "/app",
        "/auth"
      ]
    },
    "/_root-layout": {
      "filePath": "_root-layout.tsx",
      "children": [
        "/_root-layout/tutorial",
        "/_root-layout/"
      ]
    },
    "/app": {
      "filePath": "app.tsx",
      "children": [
        "/app/",
        "/app/room/$id",
        "/app/create-room/",
        "/app/edit-profile/",
        "/app/join-room/",
        "/app/profile/"
      ]
    },
    "/auth": {
      "filePath": "auth.tsx",
      "children": [
        "/auth/login",
        "/auth/signup"
      ]
    },
    "/_root-layout/tutorial": {
      "filePath": "_root-layout/tutorial.tsx",
      "parent": "/_root-layout"
    },
    "/auth/login": {
      "filePath": "auth/login.tsx",
      "parent": "/auth"
    },
    "/auth/signup": {
      "filePath": "auth/signup.tsx",
      "parent": "/auth"
    },
    "/_root-layout/": {
      "filePath": "_root-layout/index.tsx",
      "parent": "/_root-layout"
    },
    "/app/": {
      "filePath": "app/index.tsx",
      "parent": "/app"
    },
    "/app/room/$id": {
      "filePath": "app/room/$id.tsx",
      "parent": "/app",
      "children": [
        "/app/room/$id/",
        "/app/room/$id/chat/",
        "/app/room/$id/game/",
        "/app/room/$id/results/"
      ]
    },
    "/app/create-room/": {
      "filePath": "app/create-room/index.tsx",
      "parent": "/app"
    },
    "/app/edit-profile/": {
      "filePath": "app/edit-profile/index.tsx",
      "parent": "/app"
    },
    "/app/join-room/": {
      "filePath": "app/join-room/index.tsx",
      "parent": "/app"
    },
    "/app/profile/": {
      "filePath": "app/profile/index.tsx",
      "parent": "/app"
    },
    "/app/room/$id/": {
      "filePath": "app/room/$id/index.tsx",
      "parent": "/app/room/$id"
    },
    "/app/room/$id/chat/": {
      "filePath": "app/room/$id/chat/index.tsx",
      "parent": "/app/room/$id"
    },
    "/app/room/$id/game/": {
      "filePath": "app/room/$id/game/index.tsx",
      "parent": "/app/room/$id"
    },
    "/app/room/$id/results/": {
      "filePath": "app/room/$id/results/index.tsx",
      "parent": "/app/room/$id"
    }
  }
}
ROUTE_MANIFEST_END */
